version: '3.3'
services:
  # env_file: Ansible-ELK-Stack/elk.config
  mongo:
    image: docker.io/mongo:4.0
    container_name: mongo
    restart: always
    environment:
      - COMPANY=NTT
    volumes:
        - mongo:/data/db
    networks:
      - fabmedical
    ports:
      - 27017:27017

  medical-contoso-init-database:
    image: quay.io/linxianer12/medical-contoso-init-database:1.0.0
    container_name: medical-contoso-init-database
    restart: always
    environment:
      - COMPANY=NTT
      - CONTENT_API_URL=http://mongo:27017
      - MONGODB_CONNECTION='mongodb://mongo:27017/contentdb
    networks:
      - fabmedical

  medical-contoso-api:
    image: quay.io/linxianer12/medical-contoso-api:1.0.0
    container_name: medical-contoso-api
    restart: always
    environment:
      - COMPANY=NTT
      - MONGODB_CONNECTION=mongodb://mongo:27017/contentdb
    networks:
      - fabmedical
    ports:
      - 3001:3001

  medical-contoso-frontend:
    image: quay.io/linxianer12/medical-contoso-frontend:1.0.0
    container_name: medical-contoso-frontend
    restart: always
    environment:
      - COMPANY=NTT
      - CONTENT_API_URL=http://medical-contoso-api:3001
    networks:
      - fabmedical
    ports:
      - 3000:3000
    
networks:
  fabmedical:

volumes: # volume แบบใช้ในตัว dcoker machine ให้จัดการเอง
  mongo:
    driver: local